# kubernetes/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supply-chain-app
spec:
  replicas: 2 # Run two instances of our application for high availability
  selector:
    matchLabels:
      app: supply-chain-monolith
  template:
    metadata:
      labels:
        app: supply-chain-monolith
    spec:
      containers:
        - name: supply-chain-app
          image: your-docker-hub-username/supply-chain-monolith:latest # Replace with your Docker image
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service:3306/supply_chain_db
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka-service:9092
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: supply-chain-service
spec:
  selector:
    app: supply-chain-monolith
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer # Expose the service externally