# .github/workflows/ci-cd.yml
name: CI/CD Pipeline for Supply Chain Monolith

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and run tests
        run: mvn clean install -DskipDockerBuild

      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/supply-chain-monolith:latest

      - name: Deploy to Kubernetes
        if: github.ref == 'refs/heads/main'
        uses: appleboy/kubectl-action@master
        with:
          args: apply -f kubernetes/deployment.yaml
          kubeconfig_json: ${{ secrets.KUBE_CONFIG }}